export const Errors = {
  NOT_OWNER: '1',
  TX_NOT_EXIST: '2',
  TX_EXECUTED: '3',
  TX_CONFIRMED: '4',
  EMPTY_OWNERS: '5',
  INVALID_CONFIRMATIONS: '6',
  ZERO_ADDRESS: '7',
  ALREADY_OWNER: '8',
  NOT_ENOUGH_CONFIRMATIONS: '9',
  TX_FAILED: '10',
  TX_NOT_CONFIRMED: '11',

  AUCTION_NOT_STARTED: '12',
  AUCTION_NOT_ENDED: '13',
  AUCTION_STARTED: '14',
  AUCTION_NOT_ENOUGH_FUNDS_FOR_BID: '15',
  AUCTION_ENDED: '16',
  AUCTION_ZERO_BID: '17',
  AUCTION_ZERO_DURATION: '18',
  AUCTION_OWNER_BID: '19',
  AUCTION_NFT_OWNER: '20',
  AUCTION_NFT_TRANSFER_FAILED: '21',
  AUCTION_USER_HIGHEST_BIDDER: '22',
  AUCTION_USER_IS_NOT_BIDDER: '23',
  AUCTION_WITHDRAW_FAILED: '24',

  OWNABLE_ERROR: 'Ownable: caller is not the owner',
};

export default {};
